AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  amazonsnsdemosendpushnotification:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::316869381796:role/amazon-sns-demo-send-push-notification'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /amazon-sns-demo-send-push-notification
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - sg-0300d9682941e0e1d
        SubnetIds:
          - subnet-0a4e4b0bfda4bf4be
