AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pushnotificationwebpagesample:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::316869381796:role/LambdaVPC'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /push-notification-webpage-sample
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /push-notification-webpage-sample
            Method: GET
